# Generated by Django 5.2.17 on 2026-10-02 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calculation',
            fields=[
                ('id', models.AutoField(db_column='idCalculo', primary_key=True, serialize=False)),
                ('date_calc', models.DateTimeField(db_column='dataCalculo', null=True)),
                ('type_calc', models.CharField(choices=[('individual', 'Pessoa fisica'), ('company', 'Pessoa juridica')], db_column='tipoCalculo', max_length=30)),
            ],
            options={
                'db_table': 'Calculo',
                'ordering': ['-date_calc'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Emission',
            fields=[
                ('id', models.AutoField(db_column='idEmissao', primary_key=True, serialize=False)),
                ('category', models.CharField(db_column='categoria', max_length=100)),
                ('emission_value', models.DecimalField(db_column='valorEmissao', decimal_places=2, max_digits=12)),
                ('emission_percentage', models.DecimalField(db_column='percentualEmissao', decimal_places=2, max_digits=5, null=True)),
            ],
            options={
                'db_table': 'Emissao',
                'ordering': ['-emission_value'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CalculationCompany',
            fields=[
                ('calculation', models.OneToOneField(db_column='idCalculoEmpresa', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='company_details', serialize=False, to='calculations.calculation')),
                ('name_company', models.CharField(db_column='nomeEmpresa', max_length=150)),
                ('num_employee', models.PositiveIntegerField(db_column='numeroFuncionarios', null=True)),
                ('energy', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('transport_fleet', models.DecimalField(db_column='frotaTransporte', decimal_places=2, max_digits=10, null=True)),
                ('diesel', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('travels_corporate', models.DecimalField(db_column='viagensCorporativas', decimal_places=2, max_digits=10, null=True)),
                ('waste', models.DecimalField(db_column='residuos', decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'CalculoEmpresa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CalculationIndividual',
            fields=[
                ('calculation', models.OneToOneField(db_column='idCalculoPessoa', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='individual_details', serialize=False, to='calculations.calculation')),
                ('travels_plane', models.DecimalField(db_column='viagensAviao', decimal_places=2, max_digits=10, null=True)),
                ('energy', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('fuel', models.DecimalField(db_column='combustivel', decimal_places=2, max_digits=10, null=True)),
                ('transport', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('water', models.DecimalField(db_column='agua', decimal_places=2, max_digits=10, null=True)),
                ('waste', models.DecimalField(db_column='residuos', decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'CalculoPessoa',
                'managed': False,
            },
        ),
    ]
